apiVersion: tomato.github.com/v1
kind: MySQL
metadata:
  labels:
    app.kubernetes.io/name: mysqlcrd
    app.kubernetes.io/managed-by: kustomize
  name: mysql-sample
  namespace: tomato
spec:
  #主库配置
  master:
    rootPassword: root
    replicaAccount: master0
    replicaPassword: Master@
  #从库配置
  replica:
    # 从库数量
    size: 2
  # 磁盘配置
  storageClassName: standard
  storage: 2Gi
  # cpu配置
  cpu: 100m
  # 内存配置
  memory: 128Mi
